name: CI
on: push
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt .

      - name: Create coverage directory
        run: mkdir -p coverage

      - name: Test with Pytest
        run: |
          python3 -m pytest --cov=inflammation.models --cov-report=term-missing tests/test_models.py
          python3 -m coverage json -o coverage.json

      - name: Check style with Pylint
        run: |
          python3 -m pylint --fail-under=0 --reports=y inflammation

      - name: Update Coverage Badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
        with:
          coverage-file: coverage.json
          working-directory: ${{ github.workspace }}
